### ISSUE TITLE
    raise Exception.Create('GetSym: EOF!!! previous was: ' + fSym);

### ISSUE THREAD

**Issue by limelect** [DaveBlakeman/DelphiUsesGraph#1]
Tried to analyze JsonDataObjects.pas
and got     raise Exception.Create('GetSym: EOF!!! previous was: ' + fSym);
Main the same

compile with D10.2.3
I use ahausladen/JsonDataObjects

**Comment by DaveBlakeman** [comment]
Hi,

I can't reproduce this, but the error is probably from trying to open an empty file. I've tightened up the checking to report more information in the log, if you'd like to try again.

**Comment by limelect** [comment]
Now it works
