### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by lhengen** [DaveBlakeman/DelphiUsesGraph#2]
Just got the latest code and tried to compile it under 10.4.  Had the following issues:

1) Main.pas has RzTabs in the interface uses clause.  I removed it.
2) The project makes use of Andreas Hausladen's project https://github.com/ahausladen/JsonDataObjects
 yet I didn't see any mention of it is made in the Read.Me.  Thankfully Google is my friend.

Minor issues, just thought I would let you know.

Would be nice to enhance the UI to grab search paths from Delphi, and have some way of browsing folders to add them to the search list.  

As advertised it is a blazing fast & useful tool.  Thanks for open sourcing it!

**Comment by DaveBlakeman** [comment]
Thanks Larry,

I've fixed these issues. We use JsonDataObjects as it's massively quicker than System.JSON for large structures, but in this case I don't ever see project settings getting big, so I've gone back to using System.JSON for easier portability.

I'm pretty tight on time right now, but they're both good suggestions.
